### PR TITLE
[BUGFIX] Fix first-child and last-child selectors

### LINKED ISSUE #51: :first-child and :last-child selectors do not add CSS
There were 2 failures:

 1) Pelago\Tests\Unit\EmogrifierTest::emogrifierMatchesSelectors with data set "BODY:first-child matches first child" ('body:first-child {color: red} ', '#<p class="p-1" style="color: red">#')
 Failed asserting that '<!DOCTYPE html>
<html id="html"><body>    <p class="p-1"><span>some text</span></p>    <p class="p-2"><span title="bonjour">some</span> text</p>    <p class="p-3">some more text</p>  </body></html>
' matches PCRE pattern "#<p class="p-1" style="color: red">#".

/home/klee/eclipse/emogrifier/Tests/Unit/EmogrifierTest.php:370

2) Pelago\Tests\Unit\EmogrifierTest::emogrifierMatchesSelectors with data set "BODY:last-child matches last child" ('body:last-child {color: red} ', '#<p class="p-3" style="color: red">#')
Failed asserting that '<!DOCTYPE html>
<html id="html"><body>    <p class="p-1"><span>some text</span></p>    <p class="p-2"><span title="bonjour">some</span> text</p>    <p class="p-3">some more text</p>  </body></html>
' matches PCRE pattern "#<p class="p-3" style="color: red">#".

/home/klee/eclipse/emogrifier/Tests/Unit/EmogrifierTest.php:370

FAILURES!
Tests: 57, Assertions: 57, Failures: 2.

This is for the following lines in selectorDataProvider:

            'BODY:first-child matches first child'
                => array('body:first-child {' . $styleRule . '} ', '#<p class="p-1" style="' . $styleRule . '">#'),
            'BODY:first-child not matches middle child' => array('body:first-child {' . $styleRule . '} ', '#<p class="p-2">#'),
            'BODY:first-child not matches last child' => array('body:first-child {' . $styleRule . '} ', '#<p class="p-3">#'),
            'BODY:last-child not matches first child' => array('body:last-child {' . $styleRule . '} ', '#<p class="p-1">#'),
            'BODY:last-child not matches middle child' => array('body:last-child {' . $styleRule . '} ', '#<p class="p-2">#'),
            'BODY:last-child matches last child' => array('body:last-child {' . $styleRule . '} ', '#<p class="p-3" style="' . $styleRule . '">#'),

### LINKED ISSUE #192: parseNth does nonsense with $multiplier
$multiplier is an int. So doing strlen does not make sense. We should cover this with unit tests first, though, so we can be sure we don't break anything.

### PR DESCRIPTION
**Pull request by oliverklee**
Fixes #51
Fixes #192

### CODE REVIEW

**Comment by jjriv** [comment]
-
-The following selectors are implemented, but currently are broken:
-
  * first-child (currently broken)
  * last-child (currently broken)

I'm confused. Are these selectors still broken or not? We are removing the comment saying they are broken, and the PR says this bug is getting fixed, but inside the parens it still says "currently broken".

**Comment by jjriv** [comment]
self::assertRegExp(
-            $containedHtml,
-            $this->subject->emogrify()
+            $htmlRegularExpression,
+            $result
         );

According to the docs, $result should be a string:
https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertRegExp

But I don't see where $result is getting assigned any value before being passed to assertRegExp()

**Comment by oliverklee** [comment]
I've just removed the two "(currently broken)" from the docs. I'll look into the $result thing now.

**Comment by oliverklee** [comment]
$result is string because it gets assigned the return value of $this->subject->emogrify().

And I put it into a local variable to separate the execution from the verification according to the four-phase test concept: https://robots.thoughtbot.com/four-phase-test

**Comment by oliverklee** [comment]
I've just pushed the changes.

**Pull request merged**
