### PR TITLE
Adds a range of features including state selectors and namespace overrides

### PR DESCRIPTION
**Pull request by peterfox**
I was working for a company that needed a PHP library that worked in a similar way to https://github.com/premailer/premailer so I made a few changes to the existing library.

I added a few features (and accompanying tests) that work quite well.

State Selector filtering - Copies all uses of :hover, :active, :visited and :link selectors into it's own style node preserving them

Namespace overrides - If you apply classes to a node and one has .padding-top :10px and the next has padding: 5px; it should actually remove the padding-top:10px by how most CSS processing behaves.

Add Style nodes to Body - Some email clients will ignore style nodes in the head and therefore it's better to store them inside the body by default and set adding to the head as a secondary option.

Add a copy of CSS to the document - Some email clients still use CSS over inlined styles so it's nice to have it but there is also an option to turn it off.

Currently using my modified version in https://github.com/peterfox/php-inliner and it would be nice to lock these features down in the original repo if possible.

### CODE REVIEW

**Comment by oliverklee** [comment]
Hi @peterfox, thanks a lot for this PR! :heart: 

I'd prefer to have only one feature/bugfix/Issue per PR.

Could you please split this up into one PR per feature, make sure that the automated tests are green and also squash your commits so that there is only one commit per PR?

You can find more information on this in the contribution document: https://github.com/jjriv/emogrifier/blob/master/CONTRIBUTING.md

Thanks again!


Oliver

**Comment by oliverklee** [comment]
@peterfox Any news on this PR (particularly on splitting it up into separate PRs, one per issue/feature)?

**Comment by peterfox** [comment]
Hey, yes, I plan to do it but just haven't had too much time to do so currently with Christmas and all plus other projects I'm working on.

**Comment by oliverklee** [comment]
Great, thanks for the heads-up! Enjoy the holidays! :christmas_tree:

**Comment by oliverklee** [comment]
@peterfox Any news on this PR?

**Comment by peterfox** [comment]
@oliverklee sorry, I completely let this get away from me, I'll try and schedule some time to get this done

**Comment by oliverklee** [comment]
Thanks!

**Comment by oliverklee** [comment]
Closing this PR as I won't be able to merge it with all the features and fixed mixed up. @peterfox Could you please open separate PRs, one for each feature/fix? Thanks!

**Pull request closed without merging**
