### PR TITLE
[BUGFIX] Ignore value with words more than one in the attribute selector

### PR DESCRIPTION
**Pull request by taiyonoryoshy**
Fixes #327

### CODE REVIEW

**Comment by oliverklee** [comment]
Isn't this the same as #326?

**Comment by oliverklee** [comment]
I see that you work on your master. I recommend that you open a separate branch for each PR. This allows you to work on more than one PR at the same time, and also to keep a clean master which you can easily regularly  rebase to upstream.

**Comment by oliverklee** [comment]
@taiyonoryoshy for updating a PR, you can update your commit (either by doing commit --amend, or via squashing) and then force-push the branch (push -f). This will update the PR. Then you do not need to create a new PR if you update your contribution.

**Comment by oliverklee** [comment]
Could you also please add test cases for the new behavior (including all relevant edge cases)? Thanks!

**Comment by taiyonoryoshy** [comment]
@oliverklee I did force-push

**Comment by oliverklee** [comment]
Merged. @taiyonoryoshy Thank a lot for contributing this bug fix! ❤️

**Pull request merged**
