### PR TITLE
Proposal: better formatting of preg_replace rules in translates ToXpath

### PR DESCRIPTION
**Pull request by OzzyCzech**
Check way of formatting preg_replace rules that we use in our projects

This PR is just proposal - if you don't like that, never mind :-D close it without merge...

### CODE REVIEW

**Comment by oliverklee** [comment]
Hi @OzzyCzech, thanks for the PR! I like the new formatting, and I would also like to keep the descriptions (which currently are the array keys). Any ideas how to combine both?

**Comment by OzzyCzech** [comment]
I am add extra space to be easily read, what do you thing about that?

**Comment by oliverklee** [comment]
I don't think we need the extra spacing or the blank lines as they spread the code too far to be readble. However, I really like the comment lines. :-)

So I propose getting rid of the extra spaces while keeping the comment lines (on separate lines so we don't have any end-of-line comments).

**Comment by OzzyCzech** [comment]
done...

**Comment by oliverklee** [comment]
Hi @OzzyCzech, I've polished your PR a bit and merged it as #281. Thanks a bunch for contributing! :heart:

**Pull request closed without merging**
