### PR TITLE
[FEATURE] Support the attr$=value selector

### PR DESCRIPTION
**Pull request by taiyonoryoshy**

### CODE REVIEW

**Comment by oliverklee** [comment]
@taiyonoryoshy Thanks, the PR looks good! Could you please rebase it to resolve the merge conflicts? Then I'll merge it.

**Comment by taiyonoryoshy** [comment]
@oliverklee I did rebase it to resolve the merge conflicts.

**Comment by taiyonoryoshy** [comment]
@oliverklee what about my PR?

**Comment by oliverklee** [comment]
@taiyonoryoshy I've just returned from a vacation and merged your PR. Thanks for contributing! :heart:

**Pull request merged**
