### PR TITLE
[FEATURE] Cache combinedStyles

### PR DESCRIPTION
**Pull request by vanderlee**
Same as #208, but on current master.

The current master with the short array fix caused so much changes that it was easier to just start anew with this feature than try to resolve all the conflicts.

I also added the clearing of the cache, which decreases performance gains somewhat: back to ~20% from ~30%.

### CODE REVIEW

**Comment by oliverklee** [comment]
Looks good. If you remove the trailing space (thus making the build pass), I'll directly merge it. :heart: 

(I would need to create an new PR if I wanted to edit a PR from a fork. So it's less work for me if you do the change.)

**Comment by oliverklee** [comment]
By the way, you can configure most IDEs (including PhpStorm) to automatically drop any trailing whitespace on saving a file.

**Comment by vanderlee** [comment]
Squashed and somehow had to fix a totally new /r/n error on a line I never touched (the very first).

**Comment by oliverklee** [comment]
Merged. @vanderlee Thanks a lot for this PR!

**Pull request merged**
