### PR TITLE
[TASK] Stop encoding umlauts and dollar signs

### LINKED ISSUE #98: Emogrifier turns $ into %24 unexpectedly
I use merge tags in my email bulletins to customize their content, for example to show the name of the recipient, I use the string $[USER:NAME]$ and then I replace it with the name. 
If I place the merge tag wrapped in a span or div, there is no inconvenience, but if the merge tag is inside an attribute, let's say an href, emogrifier turns the '$' symbol to '%24' and '[' to '%5B' respectively.
If my original html is   ```<a href="$[LINK:EVENT]$">LINK</a>``` emogrifier turns it into  ```<a href="%24%5BLINK:EVENT%5D%24">LINK</a>```

Any advice to avoid this behavior?

### LINKED ISSUE #143: Drop the automatic conversion to HTML entities

### PR DESCRIPTION
**Pull request by oliverklee**
This also removes the configuration option
preserveEncoding.

Fixes #98
Fixes #143

### CODE REVIEW

**Comment by oliverklee** [comment]
@jjriv Could you please review and merge this PR? Thanks!

**Comment by jjriv** [comment]
Looks like something broke?

[https://0.gravatar.com/avatar/3ab7ce512822984d7049428dd23ab0c3?s=40&d=https%3A%2F%2Ftravis-ci.org%2Fimages%2Fmailer%2Fmascot-avatar-40px.png]jjriv / emogrifier<http://clicks.travis-ci.org/track/click/30007208/travis-ci.org?p=eyJzIjoidElwXzgzVWM2ZFZkMk0xSTZRT3htam8yd1U4IiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYXZpcy1jaS5vcmdcXFwvampyaXZcXFwvZW1vZ3JpZmllclwiLFwiaWRcIjpcImRkMjBlMzk2ZGVlMTRmNzlhZDZlYjYxMGE3MzViNmU4XCIsXCJ1cmxfaWRzXCI6W1wiYzA1YjgxN2Y1ZTdmY2E5ZjExN2UwYTlhNTlmZjI3NDk4ZjdjYzdkMFwiXX0ifQ> (master<http://clicks.travis-ci.org/track/click/30007208/github.com?p=eyJzIjoiNEloUGhxcGZia0hrR1dHUUV3c1JPUWNmaTdzIiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2dpdGh1Yi5jb21cXFwvampyaXZcXFwvZW1vZ3JpZmllclxcXC90cmVlXFxcL21hc3RlclwiLFwiaWRcIjpcImRkMjBlMzk2ZGVlMTRmNzlhZDZlYjYxMGE3MzViNmU4XCIsXCJ1cmxfaWRzXCI6W1wiMzA1YzNiNjU5OWQ2YTAyNTQ5ODRkNTBlYzBlMmU3OWNlMWU3ZjgzNlwiXX0ifQ>)


[https://travis-ci.org/images/mailer/error.png]

Build #392 has errored.<http://clicks.travis-ci.org/track/click/30007208/travis-ci.org?p=eyJzIjoiUTNjMExvRjY1U1RTV2FpZzJaT1dhV054VWhJIiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYXZpcy1jaS5vcmdcXFwvampyaXZcXFwvZW1vZ3JpZmllclxcXC9idWlsZHNcXFwvNjYzOTkwNDdcIixcImlkXCI6XCJkZDIwZTM5NmRlZTE0Zjc5YWQ2ZWI2MTBhNzM1YjZlOFwiLFwidXJsX2lkc1wiOltcIjVjYTc2YWM5N2Q5YmNhYTY3Y2IxMWY0ZThkYjQ3Y2Y3OTQ4NDlhNGJcIl19In0>[https://travis-ci.org/images/mailer/arrow-error.png]

[https://travis-ci.org/images/mailer/stopwatch-error.png]
26 seconds

[https://secure.gravatar.com/avatar/3ab7ce512822984d7049428dd23ab0c3?s=15&d=https%3A%2F%2Ftravis-ci.org%2Fimages%2Fmailer%2Fmascot-avatar-15px.png]

John Reeve

82a0208<http://clicks.travis-ci.org/track/click/30007208/github.com?p=eyJzIjoiUmd3QmtpNlFOUW9pbllZUEx5QU12dmVFb1NjIiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2dpdGh1Yi5jb21cXFwvampyaXZcXFwvZW1vZ3JpZmllclxcXC9jb21taXRcXFwvODJhMDIwODYyMjNkZGZkNzJlNWNkMTc0OGQzNDllNzYzNmMxZDQ2YVwiLFwiaWRcIjpcImRkMjBlMzk2ZGVlMTRmNzlhZDZlYjYxMGE3MzViNmU4XCIsXCJ1cmxfaWRzXCI6W1wiNTBkYjI5YjA3MjNmYWY4YzU3MGQ3MmUzYzQ2ZmY3ZGI3MDgzMWExN1wiXX0ifQ> Changeset →<http://clicks.travis-ci.org/track/click/30007208/github.com?p=eyJzIjoiUF9uS0tTUTJ4bU0wZFBpV0hZWlRqLW1hREhzIiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2dpdGh1Yi5jb21cXFwvampyaXZcXFwvZW1vZ3JpZmllclxcXC9jb21wYXJlXFxcL2I5NmFiMGNlNGE3ZC4uLjgyYTAyMDg2MjIzZFwiLFwiaWRcIjpcImRkMjBlMzk2ZGVlMTRmNzlhZDZlYjYxMGE3MzViNmU4XCIsXCJ1cmxfaWRzXCI6W1wiYTI3NmFhYTExOTQ3YmY2ODE2NWM4NGFkNGQxY2Q4NmNmMGQwYzE3NlwiXX0ifQ>



Merge pull request #170 from jjriv/task/remove-entities

[TASK] Stop encoding umlauts and dollar signs


Want to know about upcoming build environment updates?

Would you like to stay up-to-date with the upcoming Travis CI build environment updates? We set up a mailing list for you! Sign up here<http://clicks.travis-ci.org/track/click/30007208/eepurl.com?p=eyJzIjoibHlOTElFM0RIYzBmSElsMkVHeFowaEphbjF3IiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvZWVwdXJsLmNvbVxcXC85T0NzUFwiLFwiaWRcIjpcImRkMjBlMzk2ZGVlMTRmNzlhZDZlYjYxMGE3MzViNmU4XCIsXCJ1cmxfaWRzXCI6W1wiMTEwZTdlYThkN2Y5YjA5NDdlYWJiMzQ3NmYyMDBkMmI2NTRkZjMyNlwiXX0ifQ>.
[https://travis-ci.org/images/mailer/email-footer-travis-logo.png]

Documentation<http://clicks.travis-ci.org/track/click/30007208/docs.travis-ci.com?p=eyJzIjoiaUFqUzhYYmlYVU1hOW9Qd2xFWW5VUEhpdGZjIiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvZG9jcy50cmF2aXMtY2kuY29tXCIsXCJpZFwiOlwiZGQyMGUzOTZkZWUxNGY3OWFkNmViNjEwYTczNWI2ZThcIixcInVybF9pZHNcIjpbXCI1ZmE3OTJiOGY5Nzk0YTkzNmU0OWZiNzcwNDI0NzJkNjU5N2ZmMDhjXCJdfSJ9> about Travis CI
For help please join our IRC channel irc.freenode.net#travis<irc://irc.freenode.net/travis>.
Choose who receives these build notification emails in your configuration file<http://clicks.travis-ci.org/track/click/30007208/docs.travis-ci.com?p=eyJzIjoiM1EwWm9pMHZOcW85ZTlTRXl0ZjhKOUxWeXBJIiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvZG9jcy50cmF2aXMtY2kuY29tXFxcL3VzZXJcXFwvbm90aWZpY2F0aW9uc1wiLFwiaWRcIjpcImRkMjBlMzk2ZGVlMTRmNzlhZDZlYjYxMGE3MzViNmU4XCIsXCJ1cmxfaWRzXCI6W1wiNGY1YzYwZDBkY2IxOGQ5ZGQzYTMwMzFkYjNjMjc1MTk4NmIyMmNhMFwiXX0ifQ>.

[https://travis-ci.org/images/mailer/travis-mascot.png]

Would you like to test your private code?

Travis Pro<http://clicks.travis-ci.org/track/click/30007208/travis-ci.com?p=eyJzIjoiQ2ZtakFVU2JqVmpESElvQlI0N0J3YlhISVpvIiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvdHJhdmlzLWNpLmNvbT91dG1fc291cmNlPWJ1aWxkX2VtYWlsX2Zvb3RlciZ1dG1fY2FtcGFpZ249dHJhdmlzLWNpLm9yZyZ1dG1fbWVkaXVtPWVtYWlsXCIsXCJpZFwiOlwiZGQyMGUzOTZkZWUxNGY3OWFkNmViNjEwYTczNWI2ZThcIixcInVybF9pZHNcIjpbXCIyMDAwYzI0MjkxOWZkYWYzNzVlNDhhM2Q5OTM4ZGY4MDc3YzZlMTk4XCJdfSJ9> could be your new best friend!

Travis CI is powered by [https://travis-ci.org/images/sponsors/bluebox-78x15.png] <http://clicks.travis-ci.org/track/click/30007208/bluebox.net?p=eyJzIjoib1N2RFJJTk9BdXFWR0pkc0FQNDZFQlNoT253IiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvYmx1ZWJveC5uZXRcIixcImlkXCI6XCJkZDIwZTM5NmRlZTE0Zjc5YWQ2ZWI2MTBhNzM1YjZlOFwiLFwidXJsX2lkc1wiOltcIjBmZTEzMmY2NGJkMjQ2ODhlMGM5MDM2MDcyNDA2NGY2NDRlMWVjMzFcIl19In0>


____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________

**Comment by oliverklee** [comment]
This is due to bug #90. Creating an oAuth token probably will fix this (#76). I tried to do this, but did not succeed. It might be possible that only the owner of the Travis project and the GitHub repository can do this. @jjriv Would you be willing to take a shot at #76 ?

**Comment by jjriv** [comment]
Yes, I can take a shot at getting a GitHub oauth token. I'll try to knock that out today or tomorrow.

____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________

**Comment by jjriv** [comment]
Oliver,

I just implemented this but I think I committed directly to master. My github skills aren't so great. THe file is here:
https://github.com/jjriv/emogrifier/blob/master/composer.json

Should the token be visible like that?

Thanks!
John

____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________

**Comment by jjriv** [comment]
Oliver,

I am officially in over my head. GitHub revoked the token. I am including their email below. If I can get you the token, can you take care of getting it working?

############################

Hello jjriv,



We noticed that a valid OAuth access token of yours was committed to a public GitHub repository. Publicly disclosing a valid access token would allow other people to interact with GitHub on your behalf, potentially altering data, your contact information, and billing data.



As a precautionary measure, we have revoked the OAuth token. A new token will need to be generated in order to continue using OAuth to authenticate to GitHub. Here are a couple of steps you can do to ensure your account security has not been compromised:



* Review any unauthorized OAuth applications, and remove any you don't recognize: https://help.github.com/articles/keeping-your-ssh-keys-and-application-access-tokens-safe/#reviewing-your-authorized-applications-oauth

* Review you security log to ensure that no other malicious activity has occured: https://help.github.com/articles/reviewing-your-security-log/



The commit in question is at https://github.com/jjriv/emogrifier/blob/d4fdf7e12971d31f223e81f0d7298cab274ce49a/composer.json



Please feel free to contact us at support@github.com<mailto:support@github.com> if you have any questions or concerns.



Thanks,

GitHub.com


____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________

**Comment by oliverklee** [comment]
You'll need to use an encrypted environment variable for this so that the token is not readable in plain text:
https://vierbergenlars.wordpress.com/2013/06/06/using-a-github-oauth-token-with-composer-travis-ci/
http://blog.simplytestable.com/creating-and-using-a-github-oauth-token-with-travis-and-composer/

However, Travis should already have a read-only GitHub oAuth token: http://blog.travis-ci.com/2013-06-17-time-for-a-vm-update/

I'll contact them on what we're doing wrong.

**Comment by oliverklee** [comment]
More info on creating and storing the token in an encrypted way:
http://www.gamez.name/avoid-github-rate-limits-when-using-composer/

**Comment by oliverklee** [comment]
http://stackoverflow.com/questions/30038697/travis-ci-is-failing-but-source-code-works-fine

**Comment by oliverklee** [comment]
@jjriv When you edit you profile and go to the item "Applications", is "Travis CI" listed there?

**Comment by jjriv** [comment]
Yes, it is.

____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________

**Comment by monstrfolk** [comment]
scr attribute on images with [ and ] are encoded to %5B and %5D. Any fix on this?

**Comment by oliverklee** [comment]
@monstrfolk Could you please open a separate issue for this including the steps to reproduce this, the actual result and the expected result? Thanks!

**Pull request merged**
